block_labels = ["needs-decision"]
delete_merged_branches = true
required_approvals = 1
status = [
  "CI (stable, x86_64-unknown-linux-gnu)",
  "CI (stable, x86_64-unknown-linux-musl)",
  "CI (beta, x86_64-unknown-linux-gnu)",
  "CI (beta, x86_64-unknown-linux-musl)",
  "CI (1.46.0, x86_64-unknown-linux-gnu)",
  "CI (1.46.0, x86_64-unknown-linux-musl)",
]
