on:
  push:
    branches: [ staging, trying, master ]
  pull_request:

name: Continuous integration

jobs:
  ci-linux:
    name: CI
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental || false }}
    strategy:
      matrix:
        # All published crates must build on stable.
        rust: [stable, beta, 1.46.0]

        # The default target we're compiling on and for.
        TARGET: [x86_64-unknown-linux-gnu, x86_64-unknown-linux-musl]

        include:
          # Test nightly but don't fail the build.
          - rust: nightly
            experimental: true
            TARGET: x86_64-unknown-linux-gnu

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.TARGET }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: check
          args: --target=${{ matrix.TARGET }}
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --target=${{ matrix.TARGET }}
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --target=${{ matrix.TARGET }}
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --target=${{ matrix.TARGET }} --examples
